app {
    avaiableBusinesses: "intrale,intrale2"
}

ktor {

}

aws {
    region: "us-east-2"
    cognito {
        userPoolId: "us-east-2_rLbLF8HCb"
        clientId : "11pm8ug3bletqjvdl4omvig43u"
    }

}