name: CI users

on:
  push:
    branches: [ main ]
  repository_dispatch:
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:

      - name: Download source code
        uses: actions/checkout@v4
      - name: JDK Setup
        uses: actions/setup-java@v2
        with:
          java-version: '11' # The JDK version to make available on the path.
          distribution: 'temurin'
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        env:
          AVAILABLE_BUISNESS: ${{ secrets.AVAILABLE_BUISNESS }}
          REGION: ${{ secrets.REGION }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: |
          cd ./src/main/resources/
          echo "paso 1"
          ESCAPED_VALUE=$(printf '%s\n' "$AVAILABLE_BUISNESS" | sed -e 's/[\/&]/\\&/g')
          echo "AVAILABLE_BUISNESS=${ESCAPED_VALUE}" | cat -v
          sed -i "s/AVAILABLE_BUISNESS/${AVAILABLE_BUISNESS}/gi" application.conf
          echo "paso 2"
          ESCAPED_VALUE=$(printf '%s\n' "$REGION" | sed -e 's/[\/&]/\\&/g')
          echo "REGION=${ESCAPED_VALUE}" | cat -v
          sed -i "s/REGION/${REGION}/gi" application.conf
          echo "paso 3"
          ESCAPED_VALUE=$(printf '%s\n' "$ACCESS_KEY_ID" | sed -e 's/[\/&]/\\&/g')
          echo "ACCESS_KEY_ID=${ESCAPED_VALUE}" | cat -v
          sed -i "s/ACCESS_KEY_ID/${ACCESS_KEY_ID}/gi" application.conf
          echo "paso 4"
          echo "SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}" | cat -v
          ESCAPED_SECRET=$(printf '%s\n' "$SECRET_ACCESS_KEY" | sed -e 's/[\/&]/\\&/g')
          echo "ESCAPED_SECRET=${ESCAPED_SECRET}" | cat -v
          sed -i "s/SECRET_ACCESS_KEY/${ESCAPED_SECRET}/gi" application.conf
          echo "paso 5"
          ESCAPED_VALUE=$(printf '%s\n' "$USER_POOL_ID" | sed -e 's/[\/&]/\\&/g')
          echo "USER_POOL_ID=${ESCAPED_VALUE}" | cat -v
          sed -i "s/USER_POOL_ID/${USER_POOL_ID}/gi" application.conf
          echo "paso 6"
          ESCAPED_VALUE=$(printf '%s\n' "$CLIENT_ID" | sed -e 's/[\/&]/\\&/g')
          echo "CLIENT_ID=${ESCAPED_VALUE}" | cat -v
          sed -i "s/CLIENT_ID/${CLIENT_ID}/gi" application.conf
          echo "paso 7"
          cat application.conf
          cd ../../../
          ./gradlew shadowJar
      - name: Deploy lambda
        uses: yvesgurcan/deploy-lambda-function@master
        with:
          package: ./build/libs/users-all.jar
          function-name: kotlinTest
          AWS_REGION: ${{ secrets.AWS_DEPLOY_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_DEPLOYER_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_DEPLOYER_SECRET_KEY }}
